[2020-05-23 23:15:58,181][INFO ][node                     ] [Vishanti] version[2.4.2], pid[10360], build[161c65a/2016-11-17T11:51:03Z]
[2020-05-23 23:15:58,193][INFO ][node                     ] [Vishanti] initializing ...
[2020-05-23 23:15:58,996][INFO ][plugins                  ] [Vishanti] modules [reindex, lang-expression, lang-groovy], plugins [], sites []
[2020-05-23 23:15:59,049][INFO ][env                      ] [Vishanti] using [1] data paths, mounts [[Windows (C:)]], net usable_space [7.5gb], net total_space [112.8gb], spins? [unknown], types [NTFS]
[2020-05-23 23:15:59,060][INFO ][env                      ] [Vishanti] heap size [990.7mb], compressed ordinary object pointers [true]
[2020-05-23 23:16:02,906][INFO ][node                     ] [Vishanti] initialized
[2020-05-23 23:16:02,906][INFO ][node                     ] [Vishanti] starting ...
[2020-05-23 23:16:04,213][INFO ][transport                ] [Vishanti] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}, {[::1]:9300}
[2020-05-23 23:16:04,223][INFO ][discovery                ] [Vishanti] elasticsearch/PkfZ450tTT-YzLmO0uhrbg
[2020-05-23 23:16:08,283][INFO ][cluster.service          ] [Vishanti] new_master {Vishanti}{PkfZ450tTT-YzLmO0uhrbg}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2020-05-23 23:16:08,473][INFO ][gateway                  ] [Vishanti] recovered [1] indices into cluster_state
[2020-05-23 23:16:09,393][INFO ][cluster.routing.allocation] [Vishanti] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[haystack][0]] ...]).
[2020-05-23 23:16:10,660][INFO ][http                     ] [Vishanti] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {[::1]:9200}
[2020-05-23 23:16:10,662][INFO ][node                     ] [Vishanti] started
[2020-05-23 23:30:07,609][WARN ][http.netty               ] [Vishanti] Caught exception while handling client http traffic, closing connection [id: 0xd5691473, /127.0.0.1:65480 => /127.0.0.1:9200]
java.io.IOException: Удаленный хост принудительно разорвал существующее подключение
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
